### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jtojnar** [wraithan/weechat_notifier#1]
What is the license?

**Comment by andir** [comment]
I already tried emailing the author about it but haven't heard back.. I must have been late last year when I tried. :/

**Comment by wraithan** [comment]
I'll toss an ISC on it or something give me a few minutes, sorry I forgot about this project

**Comment by wraithan** [comment]
@jtojnar @andir Have fun with this code, sorry it is a bit of a mess, I made it as I was learning rust, and I don't know if it still builds or works.

**Comment by andir** [comment]
Thank you for starting this. My fork diverged a bit already.. Will update
license there next time In use it.
